const BOOK = 'LIBRARY_STATE_BOOK';
const NOVEL = 'LIBRARY_STATE_NOVEL';

export const LIBRARY_STATE = { BOOK, NOVEL };

const ASC = 'ASCENDING';
const DES = 'DESCENDING';

export const CHAPTER_SORT = { ASC, DES };

const FEATURING_BOOKS = 'FEATURED_BOOKS';
const NEW_BOOKS = 'NEW_BOOKS';
const TRENDING_BOOKS = 'TRENDING_BOOKS';
const RECOMMENDING_BOOKS = 'RECOMMENDING_BOOKS';

export const BOOK_TYPE = {
  FEATURING_BOOKS, NEW_BOOKS, TRENDING_BOOKS, RECOMMENDING_BOOKS
};
